# Generated by Django 5.1.3 on 2024-12-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_content_mdiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cdate',
            field=models.DateField(auto_now=True),
        ),
    ]
