# Generated by Django 5.1.3 on 2024-12-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_content_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
