# Generated by Django 5.1.3 on 2024-12-17 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_content_cdate_remove_content_group_diary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
