# Generated by Django 5.1.3 on 2024-12-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0004_alter_content_cdate_remove_content_group_diary_and_more'),
        ('loginpage', '0002_member_created_group_member_joined_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.content')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginpage.member')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.content')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginpage.member')),
            ],
            options={
                'unique_together': {('content', 'member')},
            },
        ),
    ]
