# Generated by Django 5.1.3 on 2024-12-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard',
            name='like_members',
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='bmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='userid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
